-- --------------------------------------------------------
-- Host:                         195.88.211.140
-- Versi server:                 10.6.22-MariaDB - MariaDB Server
-- OS Server:                    Linux
-- HeidiSQL Versi:               12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- membuang struktur untuk table datamini_wpdb.wpkr_wc_order_addresses
CREATE TABLE IF NOT EXISTS `wpkr_wc_order_addresses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned NOT NULL,
  `address_type` varchar(20) DEFAULT NULL,
  `first_name` text DEFAULT NULL,
  `last_name` text DEFAULT NULL,
  `company` text DEFAULT NULL,
  `address_1` text DEFAULT NULL,
  `address_2` text DEFAULT NULL,
  `city` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `postcode` text DEFAULT NULL,
  `country` text DEFAULT NULL,
  `email` varchar(320) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `address_type_order_id` (`address_type`,`order_id`),
  KEY `order_id` (`order_id`),
  KEY `email` (`email`(191)),
  KEY `phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- Membuang data untuk tabel datamini_wpdb.wpkr_wc_order_addresses: ~266 rows (lebih kurang)
INSERT INTO `wpkr_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES
	(15, 1036, 'billing', 'Marlene', 'Brando', NULL, 'Kota Pontianak, Jl. Sepakat I', NULL, 'Pontianak', 'KB', '78124', 'ID', 'mgreallyo@quantcast.com', NULL),
	(16, 1036, 'shipping', 'Marlene', 'Brando', NULL, 'Kota Pontianak, Jl. Sepakat I', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(17, 1037, 'billing', 'Eberto', 'Nern', NULL, 'Kota Kubu Raya', NULL, 'Pontianak', 'KB', '79121', 'ID', 'enernp@weibo.com', NULL),
	(18, 1037, 'shipping', 'Eberto', 'Nern', NULL, 'Kota Kubu Raya', NULL, 'Pontianak', 'KB', '79121', 'ID', NULL, NULL),
	(19, 1038, 'billing', 'Roma', 'Langfat', NULL, 'Singkawang', NULL, 'Kota Singkawang', 'KB', '78124', 'ID', 'rlangfatq@istockphoto.com', NULL),
	(20, 1038, 'shipping', 'Roma', 'Langfat', NULL, 'Singkawang', NULL, 'Kota Singkawang', 'KB', '78124', 'ID', NULL, NULL),
	(21, 1039, 'billing', 'Alexandros', 'Korneichik', NULL, 'Mempawah', NULL, 'Kota Mempawah', 'KB', '745121', 'ID', 'akorneichikr@quantcast.com', NULL),
	(22, 1039, 'shipping', 'Alexandros', 'Korneichik', NULL, 'Mempawah', NULL, 'Kota Mempawah', 'KB', '745121', 'ID', NULL, NULL),
	(23, 1040, 'billing', 'Giuseppe', 'Gerard', NULL, 'Sintang', NULL, 'Kabupaten Sintang', 'KB', '65421', 'ID', 'ggerards@instagram.com', NULL),
	(24, 1040, 'shipping', 'Giuseppe', 'Gerard', NULL, 'Sintang', NULL, 'Kabupaten Sintang', 'KB', '65421', 'ID', NULL, NULL),
	(25, 1041, 'billing', 'Angelique', 'Brosius', NULL, 'Jalan Demang Akub', NULL, 'Singkawang', 'KB', '78124', 'ID', 'abrosiust@sun.com', NULL),
	(26, 1041, 'shipping', 'Angelique', 'Brosius', NULL, 'Jalan Demang Akub', NULL, 'Singkawang', 'KB', '78124', 'ID', NULL, NULL),
	(27, 1042, 'billing', 'Jessy', 'De Bell', NULL, 'Kota Pontianak, Jl. Sepakat II', NULL, 'Pontianak', 'KB', '78125', 'ID', 'jdebellu@nationalgeographic.com', NULL),
	(28, 1042, 'shipping', 'Jessy', 'De Bell', NULL, 'Kota Pontianak, Jl. Sepakat II', NULL, 'Pontianak', 'KB', '78125', 'ID', NULL, NULL),
	(29, 1043, 'billing', 'Lenna', 'Seagrove', NULL, 'Kota Mempawah', NULL, 'Kota Mempawah', 'KB', '72121', 'ID', 'lseagrovev@usa.gov', NULL),
	(30, 1043, 'shipping', 'Lenna', 'Seagrove', NULL, 'Kota Mempawah', NULL, 'Kota Mempawah', 'KB', '72121', 'ID', NULL, NULL),
	(31, 1044, 'billing', 'Estelle', 'Pieroni', NULL, 'Jalan Sungai Jawi', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'epieroniw@blogs.com', NULL),
	(32, 1044, 'shipping', 'Estelle', 'Pieroni', NULL, 'Jalan Sungai Jawi', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(33, 1045, 'billing', 'Nady', 'Veel', NULL, 'Kebayoran Baru', NULL, 'Jakarta Barat', 'JK', '9821', 'ID', 'nveelx@123-reg.co.uk', NULL),
	(34, 1045, 'shipping', 'Nady', 'Veel', NULL, 'Kebayoran Baru', NULL, 'Jakarta Barat', 'JK', '9821', 'ID', NULL, NULL),
	(35, 1046, 'billing', 'Dimitry', 'Fasset', NULL, 'Jakarta Barat', NULL, 'Kota Jakarta', 'JK', '76817', 'ID', 'dfassety@unicef.org', NULL),
	(36, 1046, 'shipping', 'Dimitry', 'Fasset', NULL, 'Jakarta Barat', NULL, 'Kota Jakarta', 'JK', '76817', 'ID', NULL, NULL),
	(37, 1047, 'billing', 'Susann', 'Langtry', NULL, 'Kota Singkawang', NULL, 'Kota Singkawang', 'KB', '76252', 'ID', 'slangtryz@indiegogo.com', NULL),
	(38, 1047, 'shipping', 'Susann', 'Langtry', NULL, 'Kota Singkawang', NULL, 'Kota Singkawang', 'KB', '76252', 'ID', NULL, NULL),
	(39, 1049, 'billing', 'Werner', 'Buchanan', NULL, 'jalan panda', NULL, 'Pontianak', 'KB', '78111', 'ID', 'wbuchanan0@reference.com', NULL),
	(40, 1049, 'shipping', 'Werner', 'Buchanan', NULL, 'jalan panda', NULL, 'Pontianak', 'KB', '78111', 'ID', NULL, NULL),
	(41, 1050, 'billing', 'Abagael', 'Cockin', NULL, 'jalan harimau', NULL, 'Pontianak', 'KB', '78112', 'ID', 'acockin1@noaa.gov', NULL),
	(42, 1050, 'shipping', 'Abagael', 'Cockin', NULL, 'jalan harimau', NULL, 'Pontianak', 'KB', '78112', 'ID', NULL, NULL),
	(43, 1051, 'billing', 'Rozanna', 'Leng', NULL, 'jalan singa', NULL, 'Pontianak', 'KB', '78113', 'ID', 'rleng2@accuweather.com', NULL),
	(44, 1051, 'shipping', 'Rozanna', 'Leng', NULL, 'jalan singa', NULL, 'Pontianak', 'KB', '78113', 'ID', NULL, NULL),
	(45, 1052, 'billing', 'Kelcey', 'Ziehms', NULL, 'jalan komodo', NULL, 'Pontianak', 'KB', '78114', 'ID', 'kziehms3@msn.com', NULL),
	(46, 1052, 'shipping', 'Kelcey', 'Ziehms', NULL, 'jalan komodo', NULL, 'Pontianak', 'KB', '78114', 'ID', NULL, NULL),
	(47, 1053, 'billing', 'Beryl', 'Beckinsale', NULL, 'jalan kucing', NULL, 'Pontianak', 'KB', '78115', 'ID', 'bbeckinsale4@vinaora.com', NULL),
	(48, 1053, 'shipping', 'Beryl', 'Beckinsale', NULL, 'jalan kucing', NULL, 'Pontianak', 'KB', '78115', 'ID', NULL, NULL),
	(49, 1054, 'billing', 'Rollins', 'Pascho', NULL, 'jalan kapibara', NULL, 'Pontianak', 'KB', '78116', 'ID', 'rpascho5@jigsy.com', NULL),
	(50, 1054, 'shipping', 'Rollins', 'Pascho', NULL, 'jalan kapibara', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(51, 1055, 'billing', 'Nada', 'Baudassi', NULL, 'jalan angsa', NULL, 'Pontianak', 'KB', '78117', 'ID', 'nbaudassi6@virginia.edu', NULL),
	(52, 1055, 'shipping', 'Nada', 'Baudassi', NULL, 'jalan angsa', NULL, 'Pontianak', 'KB', '78117', 'ID', NULL, NULL),
	(53, 1056, 'billing', 'Lorens', 'McIlvoray', NULL, 'jalan ayam', NULL, 'Pontianak', 'KB', '78118', 'ID', 'lmcilvoray7@eepurl.com', NULL),
	(54, 1056, 'shipping', 'Lorens', 'McIlvoray', NULL, 'jalan ayam', NULL, 'Pontianak', 'KB', '78118', 'ID', NULL, NULL),
	(55, 1057, 'billing', 'Hinda', 'Kemston', NULL, 'jalan gatau', NULL, 'Pontianak', 'KB', '78119', 'ID', 'hkemston8@deviantart.com', NULL),
	(56, 1057, 'shipping', 'Hinda', 'Kemston', NULL, 'jalan gatau', NULL, 'Pontianak', 'KB', '78119', 'ID', NULL, NULL),
	(57, 1058, 'billing', 'Dinnie', 'Tambling', NULL, 'jalan jalan ya', NULL, 'Pontianak', 'KB', '78110', 'ID', 'dtambling9@over-blog.com', NULL),
	(58, 1058, 'shipping', 'Dinnie', 'Tambling', NULL, 'jalan jalan ya', NULL, 'Pontianak', 'KB', '78110', 'ID', NULL, NULL),
	(59, 1059, 'billing', 'Omero', 'Bockh', NULL, 'jalan yayaya', NULL, 'Pontianak', 'KB', '71110', 'ID', 'obockha@msn.com', NULL),
	(60, 1059, 'shipping', 'Omero', 'Bockh', NULL, 'jalan yayaya', NULL, 'Pontianak', 'KB', '71110', 'ID', NULL, NULL),
	(61, 1060, 'billing', 'Keefe', 'Dymott', NULL, 'jalan maukemana', NULL, 'Pontianak', 'KB', '72110', 'ID', 'kdymottb@chicagotribune.com', NULL),
	(62, 1060, 'shipping', 'Keefe', 'Dymott', NULL, 'jalan maukemana', NULL, 'Pontianak', 'KB', '72110', 'ID', NULL, NULL),
	(63, 1068, 'billing', 'Davine', 'Grindley', NULL, 'Jl. Kenanga No. 123, Blok B', NULL, 'Bandung', 'JB', '40123', 'ID', 'dgrindley20@usatoday.com', NULL),
	(64, 1068, 'shipping', 'Davine', 'Grindley', NULL, 'Jl. Kenanga No. 123, Blok B', NULL, 'Bandung', 'JB', '40123', 'ID', NULL, NULL),
	(65, 1069, 'billing', 'Natividad', 'Cloake', NULL, 'Jl. Melati No. 45 RT 02 RW 04', NULL, 'Yogyakarta', 'YO', '55281', 'ID', 'ncloake21@sakura.ne.jp', NULL),
	(66, 1069, 'shipping', 'Natividad', 'Cloake', NULL, 'Jl. Melati No. 45 RT 02 RW 04', NULL, 'Yogyakarta', 'YO', '55281', 'ID', NULL, NULL),
	(67, 1070, 'billing', 'Skelly', 'Gallegos', NULL, 'Jl. Merdeka Barat No. 10', NULL, 'Jakarta Pusat', 'JK', '10110', 'ID', 'sgallegos22@godaddy.com', NULL),
	(68, 1070, 'shipping', 'Skelly', 'Gallegos', NULL, 'Jl. Merdeka Barat No. 10', NULL, 'Jakarta Pusat', 'JK', '10110', 'ID', NULL, NULL),
	(69, 1071, 'billing', 'Randi', 'Whatham', NULL, 'Perumahan Griya Asri Blok D3 No. 12', NULL, 'Bekasi', 'JB', '17145', 'ID', 'rwhatham23@ted.com', NULL),
	(70, 1071, 'shipping', 'Randi', 'Whatham', NULL, 'Perumahan Griya Asri Blok D3 No. 12', NULL, 'Bekasi', 'JB', '17145', 'ID', NULL, NULL),
	(71, 1072, 'billing', 'Swen', 'Wittman', NULL, 'Jl. Diponegoro No. 88', NULL, 'Surabaya', 'JI', '602665', 'ID', 'swittman24@aol.com', NULL),
	(72, 1072, 'shipping', 'Swen', 'Wittman', NULL, 'Jl. Diponegoro No. 88', NULL, 'Surabaya', 'JI', '602665', 'ID', NULL, NULL),
	(73, 1073, 'billing', 'Ambrosius', 'Beall', NULL, 'Komplek Anggrek Lestari Blok A No. 7', NULL, 'Medan', 'SU', '201551', 'ID', 'abeall25@mtv.com', NULL),
	(74, 1073, 'shipping', 'Ambrosius', 'Beall', NULL, 'Komplek Anggrek Lestari Blok A No. 7', NULL, 'Medan', 'SU', '201551', 'ID', NULL, NULL),
	(75, 1074, 'billing', 'Liza', 'Gambell', NULL, 'Jl. Kamboja No. 22', NULL, 'Semarang', 'JT', '50145', 'ID', 'lgambell26@nih.gov', NULL),
	(76, 1074, 'shipping', 'Liza', 'Gambell', NULL, 'Jl. Kamboja No. 22', NULL, 'Semarang', 'JT', '50145', 'ID', NULL, NULL),
	(77, 1075, 'billing', 'Danyelle', 'Brideaux', NULL, 'Gg. Haji Muchtar No. 9', NULL, 'Depok', 'JB', '16412', 'ID', 'dbrideaux27@mit.edu', NULL),
	(78, 1075, 'shipping', 'Danyelle', 'Brideaux', NULL, 'Gg. Haji Muchtar No. 9', NULL, 'Depok', 'JB', '16412', 'ID', NULL, NULL),
	(79, 1076, 'billing', 'Stillman', 'Schapiro', NULL, 'Jl. Dr. Wahidin Sudirohusodo No. 5', NULL, 'Makassar', 'SN', '90113', 'ID', 'sschapiro28@amazon.com', NULL),
	(80, 1076, 'shipping', 'Stillman', 'Schapiro', NULL, 'Jl. Dr. Wahidin Sudirohusodo No. 5', NULL, 'Makassar', 'SN', '90113', 'ID', NULL, NULL),
	(81, 1077, 'billing', 'Brandise', 'Ochterlony', NULL, 'Komplek Puri Indah Blok C No. 8', NULL, 'Tangerang Selatan', 'BT', '15310', 'ID', 'bochterlony29@amazon.com', NULL),
	(82, 1077, 'shipping', 'Brandise', 'Ochterlony', NULL, 'Komplek Puri Indah Blok C No. 8', NULL, 'Tangerang Selatan', 'BT', '15310', 'ID', NULL, NULL),
	(83, 1078, 'billing', 'Cornelius', 'Urvoy', NULL, 'Jl. Veteran No. 33', NULL, 'Malang', 'JI', '65145', 'ID', 'curvoy2a@ezinearticles.com', NULL),
	(84, 1078, 'shipping', 'Cornelius', 'Urvoy', NULL, 'Jl. Veteran No. 33', NULL, 'Malang', 'JI', '65145', 'ID', NULL, NULL),
	(85, 1079, 'billing', 'Vere', 'Prozescky', NULL, 'Jl. Letjen Suprapto No. 20', NULL, 'Pontianak', 'KB', '78111', 'ID', 'vprozescky2b@toplist.cz', NULL),
	(86, 1079, 'shipping', 'Vere', 'Prozescky', NULL, 'Jl. Letjen Suprapto No. 20', NULL, 'Pontianak', 'KB', '78111', 'ID', NULL, NULL),
	(87, 1080, 'billing', 'Ruthi', 'Hulse', NULL, 'Jl. Kenari No. 7, Kuningan', NULL, 'Jakarta Selatan', 'JK', '40111', 'ID', 'rhulse2c@typepad.com', NULL),
	(88, 1080, 'shipping', 'Ruthi', 'Hulse', NULL, 'Jl. Kenari No. 7, Kuningan', NULL, 'Jakarta Selatan', 'JK', '40111', 'ID', NULL, NULL),
	(89, 1081, 'billing', 'Aliza', 'Aguilar', NULL, 'Jl. Damai, Komplek Asri Lestari, Blok B, No. 12', NULL, 'Bandung', 'JB', '40222', 'ID', 'aaguilar2d@vkontakte.ru', NULL),
	(90, 1081, 'shipping', 'Aliza', 'Aguilar', NULL, 'Jl. Damai, Komplek Asri Lestari, Blok B, No. 12', NULL, 'Bandung', 'JB', '40222', 'ID', NULL, NULL),
	(91, 1082, 'billing', 'Hebert', 'Swanborrow', NULL, 'Jl. Mawar 1 Blok A No. 5', NULL, 'Bandung', 'JB', '40222', 'ID', 'hswanborrow2e@weather.com', NULL),
	(92, 1082, 'shipping', 'Hebert', 'Swanborrow', NULL, 'Jl. Mawar 1 Blok A No. 5', NULL, 'Bandung', 'JB', '40222', 'ID', NULL, NULL),
	(93, 1083, 'billing', 'Catherin', 'Cothey', NULL, 'Komplek Permata Hijau No. 18, Pasar Minggu', NULL, 'Jakarta Selatan', 'JK', '40111', 'ID', 'ccothey2f@smugmug.com', NULL),
	(94, 1083, 'shipping', 'Catherin', 'Cothey', NULL, 'Komplek Permata Hijau No. 18, Pasar Minggu', NULL, 'Jakarta Selatan', 'JK', '40111', 'ID', NULL, NULL),
	(95, 1084, 'billing', 'Valery', 'Bohills', NULL, 'JL. Perdamaian, Gg Sejahtera No. 3', NULL, 'Pontianak', 'KB', '40333', 'ID', 'vbohills2g@amazon.com', NULL),
	(96, 1084, 'shipping', 'Valery', 'Bohills', NULL, 'JL. Perdamaian, Gg Sejahtera No. 3', NULL, 'Pontianak', 'KB', '40333', 'ID', NULL, NULL),
	(97, 1085, 'billing', 'Rawley', 'Engelbrecht', NULL, 'Jl. Anggrek II No. 22', NULL, 'Denpasar', 'BA', '40666', 'ID', 'rengelbrecht2h@drupal.org', NULL),
	(98, 1085, 'shipping', 'Rawley', 'Engelbrecht', NULL, 'Jl. Anggrek II No. 22', NULL, 'Denpasar', 'BA', '40666', 'ID', NULL, NULL),
	(99, 1086, 'billing', 'Noreen', 'Dealey', NULL, 'Jl. Apel, Gang Bahagia Ujung No. 9', NULL, 'Bandung', 'JB', '40222', 'ID', 'ndealey2i@odnoklassniki.ru', NULL),
	(100, 1086, 'shipping', 'Noreen', 'Dealey', NULL, 'Jl. Apel, Gang Bahagia Ujung No. 9', NULL, 'Bandung', 'JB', '40222', 'ID', NULL, NULL),
	(101, 1087, 'billing', 'Caryl', 'Zanini', NULL, 'Perumahan Bukit Indah Blok F No. 4,', NULL, 'Pontianak', 'KB', '40333', 'ID', 'czanini2j@berkeley.edu', NULL),
	(102, 1087, 'shipping', 'Caryl', 'Zanini', NULL, 'Perumahan Bukit Indah Blok F No. 4,', NULL, 'Pontianak', 'KB', '40333', 'ID', NULL, NULL),
	(103, 1088, 'billing', 'Adamo', 'Allibon', NULL, 'Jl. Cempaka Raya No. 31,', NULL, 'Banjarmasin', 'KS', '40444', 'ID', 'aallibon2k@bing.com', NULL),
	(104, 1088, 'shipping', 'Adamo', 'Allibon', NULL, 'Jl. Cempaka Raya No. 31,', NULL, 'Banjarmasin', 'KS', '40444', 'ID', NULL, NULL),
	(105, 1089, 'billing', 'Kala', 'Ixer', NULL, 'Jl. Merdeka No. 10, Kel. Sukamaju, Kec. Sukaraja, Bandung, Jawa Barat', NULL, 'Bandung', 'JB', '40162', 'ID', 'kixer1o@senate.gov', NULL),
	(106, 1089, 'shipping', 'Kala', 'Ixer', NULL, 'Jl. Merdeka No. 10, Kel. Sukamaju, Kec. Sukaraja, Bandung, Jawa Barat', NULL, 'Bandung', 'JB', '40162', 'ID', NULL, NULL),
	(107, 1090, 'billing', 'Mindy', 'Ollier', NULL, 'JL. Anggrek, Gang Melati No. 11A', NULL, 'Manado', 'SA', '41111', 'ID', 'mollier2l@sitemeter.com', NULL),
	(108, 1090, 'shipping', 'Mindy', 'Ollier', NULL, 'JL. Anggrek, Gang Melati No. 11A', NULL, 'Manado', 'SA', '41111', 'ID', NULL, NULL),
	(109, 1091, 'billing', 'Hettie', 'Bowkett', NULL, 'Komplek Surya Kencana Blok D No. 15', NULL, 'Bekasi', 'JB', '41222', 'ID', 'hbowkett2m@gravatar.com', NULL),
	(110, 1091, 'shipping', 'Hettie', 'Bowkett', NULL, 'Komplek Surya Kencana Blok D No. 15', NULL, 'Bekasi', 'JB', '41222', 'ID', NULL, NULL),
	(111, 1092, 'billing', 'Elijah', 'Da Costa', NULL, 'Jl Dahlia No. 2', NULL, 'Semarang', 'JT', '40777', 'ID', 'edacosta2n@acquirethisname.com', NULL),
	(112, 1092, 'shipping', 'Elijah', 'Da Costa', NULL, 'Jl Dahlia No. 2', NULL, 'Semarang', 'JT', '40777', 'ID', NULL, NULL),
	(113, 1093, 'billing', 'Tommi', 'Andrioli', NULL, 'Jl. Sudirman No. 25, Kel. Kebayoran Baru, Kec. Kebayoran', NULL, 'Jakarta Selatan', 'JK', '12110', 'ID', 'tandrioli1p@google.es', NULL),
	(114, 1093, 'shipping', 'Tommi', 'Andrioli', NULL, 'Jl. Sudirman No. 25, Kel. Kebayoran Baru, Kec. Kebayoran', NULL, 'Jakarta Selatan', 'JK', '12110', 'ID', NULL, NULL),
	(115, 1094, 'billing', 'Ward', 'Dat', NULL, 'Jl. Diponegoro No. 8, Kel. Tegalrejo, Kec. Jetis', NULL, 'Yogyakarta', 'YO', '55244', 'ID', 'wdat1q@home.pl', NULL),
	(116, 1094, 'shipping', 'Ward', 'Dat', NULL, 'Jl. Diponegoro No. 8, Kel. Tegalrejo, Kec. Jetis', NULL, 'Yogyakarta', 'YO', '55244', 'ID', NULL, NULL),
	(117, 1095, 'billing', 'Gabie', 'Dyka', NULL, 'Jl. Ahmad Yani No. 77, Kel. Banjarsari, Kec. Banjarmasin Tengah', NULL, 'Banjarmasin', 'KS', '70122', 'ID', 'gdyka1r@columbia.edu', NULL),
	(118, 1095, 'shipping', 'Gabie', 'Dyka', NULL, 'Jl. Ahmad Yani No. 77, Kel. Banjarsari, Kec. Banjarmasin Tengah', NULL, 'Banjarmasin', 'KS', '70122', 'ID', NULL, NULL),
	(119, 1096, 'billing', 'Vaclav', 'Wedge', NULL, 'Jl. Gajah Mada No. 55, Kel. Klojen, Kec. Klojen', NULL, 'Malang', 'JI', '65111', 'ID', 'vwedge1s@typepad.com', NULL),
	(120, 1096, 'shipping', 'Vaclav', 'Wedge', NULL, 'Jl. Gajah Mada No. 55, Kel. Klojen, Kec. Klojen', NULL, 'Malang', 'JI', '65111', 'ID', NULL, NULL),
	(121, 1097, 'billing', 'Jenilee', 'Leggitt', NULL, '-', NULL, '-', 'PA', '142001', 'ID', 'jleggitt1c@theatlantic.com', NULL),
	(122, 1097, 'shipping', 'Jenilee', 'Leggitt', NULL, '-', NULL, '-', 'PA', '142001', 'ID', NULL, NULL),
	(123, 1098, 'billing', 'Zahara', 'Raigatt', NULL, '-', NULL, '-', 'GO', '123456', 'ID', 'zraigatt1d@skype.com', NULL),
	(124, 1098, 'shipping', 'Zahara', 'Raigatt', NULL, '-', NULL, '-', 'GO', '123456', 'ID', NULL, NULL),
	(125, 1099, 'billing', 'Fleur', 'Skyme', NULL, '-', NULL, '-', 'JB', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(126, 1099, 'shipping', 'Fleur', 'Skyme', NULL, '-', NULL, '-', 'JB', '123456', 'ID', NULL, NULL),
	(127, 1100, 'billing', 'Olive', 'O\'Logan', NULL, 'Jalan Serdam', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'oologanc@imgur.com', NULL),
	(128, 1100, 'shipping', 'Olive', 'O\'Logan', NULL, 'Jalan Serdam', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(129, 1101, 'billing', 'Fernandina', 'Affuso', NULL, 'Jalan Ahmad Yani 2', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'faffusod@twitter.com', NULL),
	(130, 1101, 'shipping', 'Fernandina', 'Affuso', NULL, 'Jalan Ahmad Yani 2', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(131, 1102, 'billing', 'Joanie', 'Mannie', NULL, 'Jalan Kota Baru', NULL, 'Kota Pontianak', 'KB', '78121', 'ID', 'jmanniee@google.com.au', NULL),
	(132, 1102, 'shipping', 'Joanie', 'Mannie', NULL, 'Jalan Kota Baru', NULL, 'Kota Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(133, 1103, 'billing', 'Klarrisa', 'Calender', NULL, 'Jalan Pal 5', NULL, 'Kota Pontianak', 'KB', '78114', 'ID', 'kcalenderf@shinystat.com', NULL),
	(134, 1103, 'shipping', 'Klarrisa', 'Calender', NULL, 'Jalan Pal 5', NULL, 'Kota Pontianak', 'KB', '78114', 'ID', NULL, NULL),
	(135, 1104, 'billing', 'Fairlie', 'Preshaw', NULL, 'Jalan Sui Jawi', NULL, 'Kota Pontianak', 'KB', '78113', 'ID', 'fpreshawg@china.com.cn', NULL),
	(136, 1104, 'shipping', 'Fairlie', 'Preshaw', NULL, 'Jalan Sui Jawi', NULL, 'Kota Pontianak', 'KB', '78113', 'ID', NULL, NULL),
	(137, 1105, 'billing', 'Corrina', 'Clubb', NULL, 'Jalan Paris 2', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'cclubbh@marketwatch.com', NULL),
	(138, 1105, 'shipping', 'Corrina', 'Clubb', NULL, 'Jalan Paris 2', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(139, 1106, 'billing', 'Rodge', 'Winram', NULL, 'Jalan Paris 1', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'rwinrami@cnn.com', NULL),
	(140, 1106, 'shipping', 'Rodge', 'Winram', NULL, 'Jalan Paris 1', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(141, 1107, 'billing', 'Ronny', 'Plews', NULL, 'Jalan Imam Bonjol', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'rplewsj@paypal.com', NULL),
	(142, 1107, 'shipping', 'Ronny', 'Plews', NULL, 'Jalan Imam Bonjol', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(143, 1108, 'billing', 'Isis', 'Griss', NULL, 'Jalan Kota Baru', NULL, 'Kota Pontianak', 'KB', '78121', 'ID', 'igrissk@addtoany.com', NULL),
	(144, 1108, 'shipping', 'Isis', 'Griss', NULL, 'Jalan Kota Baru', NULL, 'Kota Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(145, 1109, 'billing', 'Rita', 'Crownshaw', NULL, 'Jalan Serdam', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', 'rcrownshawl@cnet.com', NULL),
	(146, 1109, 'shipping', 'Rita', 'Crownshaw', NULL, 'Jalan Serdam', NULL, 'Kota Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(147, 1110, 'billing', 'Maisie', 'Gobolos', NULL, 'Jalan Kota Baru', NULL, 'Kota Pontianak', 'KB', '78114', 'ID', 'mgobolosm@who.int', NULL),
	(148, 1110, 'shipping', 'Maisie', 'Gobolos', NULL, 'Jalan Kota Baru', NULL, 'Kota Pontianak', 'KB', '78114', 'ID', NULL, NULL),
	(149, 1111, 'billing', 'Norah', 'Armfield', NULL, 'Jalan Serdam', NULL, 'Kota Pontianak', 'JB', '78124', 'ID', 'narmfieldn@cyberchimps.com', NULL),
	(150, 1111, 'shipping', 'Norah', 'Armfield', NULL, 'Jalan Serdam', NULL, 'Kota Pontianak', 'JB', '78124', 'ID', NULL, NULL),
	(151, 1115, 'billing', 'Fleur', 'Skyme', NULL, 'Jl. Pahlawan', NULL, 'Jakarta Selatan', 'JK', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(152, 1115, 'shipping', 'Fleur', 'Skyme', NULL, 'Jl. Pahlawan', NULL, 'Jakarta Selatan', 'JK', '123456', 'ID', NULL, NULL),
	(153, 1116, 'billing', 'Fleur', 'Skyme', NULL, 'Jl. Pahlawan', NULL, 'Jakarta Selatan', 'JK', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(154, 1116, 'shipping', 'Fleur', 'Skyme', NULL, 'Jl. Pahlawan', NULL, 'Jakarta Selatan', 'JK', '123456', 'ID', NULL, NULL),
	(155, 1117, 'billing', 'Lawey', 'Avivah', NULL, 'Jl. Khatulistiwa', NULL, 'Medan', 'SS', '123456', 'ID', 'alawey1f@columbia.edu', NULL),
	(156, 1117, 'shipping', 'Lawey', 'Avivah', NULL, 'Jl. Khatulistiwa', NULL, 'Medan', 'SS', '123456', 'ID', NULL, NULL),
	(157, 1118, 'billing', 'Amelina', 'Pavluk', NULL, 'Jl. Khatulistiwa', NULL, 'Medan', 'SS', '123456', 'ID', 'apavluk1j@posterous.com', NULL),
	(158, 1118, 'shipping', 'Amelina', 'Pavluk', NULL, 'Jl. Khatulistiwa', NULL, 'Medan', 'SS', '123456', 'ID', NULL, NULL),
	(159, 1119, 'billing', 'Ker', 'O\'Geaney', NULL, 'Jl. Keramat Jati', NULL, 'Palangkaraya', 'KT', '123456', 'ID', 'kogeaney1k@guardian.co.uk', NULL),
	(160, 1119, 'shipping', 'Ker', 'O\'Geaney', NULL, 'Jl. Keramat Jati', NULL, 'Palangkaraya', 'KT', '123456', 'ID', NULL, NULL),
	(161, 1120, 'billing', 'Debora', 'Carthy', NULL, 'Jl. Keramat Jati', NULL, 'Palangkaraya', 'KT', '123456', 'ID', 'dcarthy1l@gmpg.org', NULL),
	(162, 1120, 'shipping', 'Debora', 'Carthy', NULL, 'Jl. Keramat Jati', NULL, 'Palangkaraya', 'KT', '123456', 'ID', NULL, NULL),
	(163, 1121, 'billing', 'Kalila', 'Rostron', NULL, 'Jl. Professor Ahmad Dahlan', NULL, 'Palangkaraya', 'KT', '123456', 'ID', 'krostron1m@ocn.ne.jp', NULL),
	(164, 1121, 'shipping', 'Kalila', 'Rostron', NULL, 'Jl. Professor Ahmad Dahlan', NULL, 'Palangkaraya', 'KT', '123456', 'ID', NULL, NULL),
	(165, 1122, 'billing', 'Elijah', 'Da Costa', NULL, 'Jl Putri daranante no 17', NULL, 'Pontianak', 'KB', '78116', 'ID', 'edacosta2n@acquirethisname.com', NULL),
	(166, 1122, 'shipping', 'Elijah', 'Da Costa', NULL, 'Jl Putri daranante no 17', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(167, 1123, 'billing', 'Benton', 'Farrance', NULL, 'Jl. Professor Ahmad Dahlan', NULL, 'Palangkaraya', 'KT', '123456', 'ID', 'krostron1m@ocn.ne.jp', NULL),
	(168, 1123, 'shipping', 'Benton', 'Farrance', NULL, 'Jl. Professor Ahmad Dahlan', NULL, 'Palangkaraya', 'KT', '123456', 'ID', NULL, NULL),
	(169, 1124, 'billing', 'Bethina', 'Muston', NULL, 'Jl alianyang no 1', NULL, 'Pontianak', 'KB', '78116', 'ID', 'bmuston2o@altervista.org', NULL),
	(170, 1124, 'shipping', 'Bethina', 'Muston', NULL, 'Jl alianyang no 1', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(171, 1125, 'billing', 'Tracee', 'Ashwood', NULL, 'Jl. Keramat Jati', NULL, 'Balikpapan', 'KI', '123456', 'ID', 'tashwood1i@cafepress.com', NULL),
	(172, 1125, 'shipping', 'Tracee', 'Ashwood', NULL, 'Jl. Keramat Jati', NULL, 'Balikpapan', 'KI', '123456', 'ID', NULL, NULL),
	(173, 1126, 'billing', 'Zelda', 'Attarge', NULL, 'Jl purnama 1 komp purnama 5', NULL, 'Pontianak', 'KB', '78121', 'ID', 'zattarge2p@hostgator.com', NULL),
	(174, 1126, 'shipping', 'Zelda', 'Attarge', NULL, 'Jl purnama 1 komp purnama 5', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(175, 1127, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(176, 1127, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(177, 1128, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(178, 1128, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(179, 1129, 'billing', 'Clarey', 'Badwick', NULL, 'Jl purnama1 gg purnama 1', NULL, 'Pontianak', 'KB', '78121', 'ID', 'cbadwick2q@ox.ac.uk', NULL),
	(180, 1129, 'shipping', 'Clarey', 'Badwick', NULL, 'Jl purnama1 gg purnama 1', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(181, 1130, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(182, 1130, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(183, 1131, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(184, 1131, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(185, 1132, 'billing', 'Catarina', 'Kingsnod', NULL, 'jl karya baru no 3', NULL, 'Pontianak', 'KB', '78121', 'ID', 'ckingsnod2r@cnet.com', NULL),
	(186, 1132, 'shipping', 'Catarina', 'Kingsnod', NULL, 'jl karya baru no 3', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(187, 1133, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(188, 1133, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(189, 1134, 'billing', 'Tobiah', 'Loyd', NULL, 'Jl.Batikan', NULL, 'Yogyakarta', 'YO', '55161', 'ID', 'tloyd10@sogou.com', NULL),
	(190, 1134, 'shipping', 'Tobiah', 'Loyd', NULL, 'Jl.Batikan', NULL, 'Yogyakarta', 'YO', '55161', 'ID', NULL, NULL),
	(191, 1135, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(192, 1135, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(193, 1136, 'billing', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', 'ygrimster1h@timesonline.co.uk', NULL),
	(194, 1136, 'shipping', 'Ysabel', 'Grimster', NULL, 'Jl. Kedondong Timur', NULL, 'Samarinda', 'KI', '123456', 'ID', NULL, NULL),
	(195, 1137, 'billing', 'Dacie', 'Leeman', NULL, 'Jl M sohor', NULL, 'Pontianak', 'KB', '78121', 'ID', 'dleeman0@hatena.ne.jp', NULL),
	(196, 1137, 'shipping', 'Dacie', 'Leeman', NULL, 'Jl M sohor', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(197, 1138, 'billing', 'Tully', 'Guiraud', NULL, 'Jl. Kapas', NULL, 'Yogyakarta', 'YO', '55161', 'ID', 'tguiraud11@dropbox.com', NULL),
	(198, 1138, 'shipping', 'Tully', 'Guiraud', NULL, 'Jl. Kapas', NULL, 'Yogyakarta', 'YO', '55161', 'ID', NULL, NULL),
	(199, 1139, 'billing', 'Giana', 'Pesterfield', NULL, 'Jl putri darahitam', NULL, 'Pontianak', 'KB', '78116', 'ID', 'gpesterfield1@prlog.org', NULL),
	(200, 1139, 'shipping', 'Giana', 'Pesterfield', NULL, 'Jl putri darahitam', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(201, 1140, 'billing', 'Budi', 'Ari', NULL, 'Jl. Imam Bonjol', NULL, 'Gorontalo', 'GO', '123456', 'ID', 'budiari@gmail.com', NULL),
	(202, 1140, 'shipping', 'Budi', 'Ari', NULL, 'Jl. Imam Bonjol', NULL, 'Gorontalo', 'GO', '123456', 'ID', NULL, NULL),
	(203, 1141, 'billing', 'Muffin', 'Endean', NULL, 'Jl penjara', NULL, 'Pontianak', 'KB', '78116', 'ID', 'mendean2@w3.org', NULL),
	(204, 1141, 'shipping', 'Muffin', 'Endean', NULL, 'Jl penjara', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(205, 1142, 'billing', 'Yolanda', 'Ewenson', NULL, 'Jl. Rara Mendut', NULL, 'Yogyakarta', 'YO', '55161', 'ID', 'yewenson12@yahoo.co.jp', NULL),
	(206, 1142, 'shipping', 'Yolanda', 'Ewenson', NULL, 'Jl. Rara Mendut', NULL, 'Yogyakarta', 'YO', '55161', 'ID', NULL, NULL),
	(207, 1143, 'billing', 'Budi', 'Ari', NULL, 'Jl. Imam Bonjol', NULL, 'Gorontalo', 'GO', '123456', 'ID', 'budiari@gmail.com', NULL),
	(208, 1143, 'shipping', 'Budi', 'Ari', NULL, 'Jl. Imam Bonjol', NULL, 'Gorontalo', 'GO', '123456', 'ID', NULL, NULL),
	(209, 1144, 'billing', 'Jasmine', 'Abrahamson', NULL, 'Jl sepakat 2', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jabrahamson3@ehow.com', NULL),
	(210, 1144, 'shipping', 'Jasmine', 'Abrahamson', NULL, 'Jl sepakat 2', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(211, 1145, 'billing', 'Effie', 'Guillain', NULL, 'Jl. Rawa Bebek', NULL, 'Jakarta', 'JK', '14310', 'ID', 'eguillain13@utexas.edu', NULL),
	(212, 1145, 'shipping', 'Effie', 'Guillain', NULL, 'Jl. Rawa Bebek', NULL, 'Jakarta', 'JK', '14310', 'ID', NULL, NULL),
	(213, 1146, 'billing', 'Jacquelynn', 'Propper', NULL, 'Jl sepakat 2 ujung', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jpropper4@wunderground.com', NULL),
	(214, 1146, 'shipping', 'Jacquelynn', 'Propper', NULL, 'Jl sepakat 2 ujung', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(215, 1147, 'billing', 'Leupold', 'Djekovic', NULL, 'Tanah Abang', NULL, 'Jakarta', 'JK', '10210', 'ID', 'ldjekovic14@digg.com', NULL),
	(216, 1147, 'shipping', 'Leupold', 'Djekovic', NULL, 'Tanah Abang', NULL, 'Jakarta', 'JK', '10210', 'ID', NULL, NULL),
	(217, 1148, 'billing', 'Alixx', 'Billet', NULL, 'jl padat karya', NULL, 'Pontianak', 'KB', '78124', 'ID', 'abillett5@newsvine.com', NULL),
	(218, 1148, 'shipping', 'Alixx', 'Billet', NULL, 'jl padat karya', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(219, 1149, 'billing', 'Clyde', 'Licas', NULL, 'Setia Budi', NULL, 'Jakarta', 'JK', '12940', 'ID', 'clicas15@hostgator.com', NULL),
	(220, 1149, 'shipping', 'Clyde', 'Licas', NULL, 'Setia Budi', NULL, 'Jakarta', 'JK', '12940', 'ID', NULL, NULL),
	(221, 1152, 'billing', 'Jacquie', 'Cellier', NULL, 'Solo', NULL, 'Solo', 'JT', '57661', 'ID', 'jcellier16@twitpic.com', NULL),
	(222, 1152, 'shipping', 'Jacquie', 'Cellier', NULL, 'Solo', NULL, 'Solo', 'JT', '57661', 'ID', NULL, NULL),
	(223, 1153, 'billing', 'Jaqcuelin', 'Klaff', NULL, 'Jl reformasi', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jklaff6@phpbb.com', NULL),
	(224, 1153, 'shipping', 'Jaqcuelin', 'Klaff', NULL, 'Jl reformasi', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(225, 1154, 'billing', 'Carita', 'Eastmead', NULL, 'Magelang', NULL, 'Magelang', 'JT', '56152', 'ID', 'ceastmead17@ft.com', NULL),
	(226, 1154, 'shipping', 'Carita', 'Eastmead', NULL, 'Magelang', NULL, 'Magelang', 'JT', '56152', 'ID', NULL, NULL),
	(227, 1155, 'billing', 'Libbey', 'Windus', NULL, 'Magelang', NULL, 'Magelang', 'JT', '51652', 'ID', 'lwindus18@aboutads.info', NULL),
	(228, 1155, 'shipping', 'Libbey', 'Windus', NULL, 'Magelang', NULL, 'Magelang', 'JT', '51652', 'ID', NULL, NULL),
	(229, 1156, 'billing', 'Dephine', 'Arntzen', NULL, 'jl alianyang no 7', NULL, 'Pontianak', 'KB', '78116', 'ID', 'darntzen7@weibo.com', NULL),
	(230, 1156, 'shipping', 'Dephine', 'Arntzen', NULL, 'jl alianyang no 7', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(231, 1157, 'billing', 'Clarette', 'Siddaley', NULL, 'Jl. Kesawan', NULL, 'Medan', 'SU', '20111', 'ID', 'csiddaley19@sitemeter.com', NULL),
	(232, 1157, 'shipping', 'Clarette', 'Siddaley', NULL, 'Jl. Kesawan', NULL, 'Medan', 'SU', '20111', 'ID', NULL, NULL),
	(233, 1158, 'billing', 'Bethina', 'Muston', NULL, 'Jl alianyang no 1', NULL, 'Pontianak', 'KB', '78116', 'ID', 'bmuston2o@altervista.org', NULL),
	(234, 1158, 'shipping', 'Bethina', 'Muston', NULL, 'Jl alianyang no 1', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(235, 1159, 'billing', 'Zelda', 'Attarge', NULL, 'Jl purnama 1 komp purnama 5', NULL, 'Pontianak', 'KB', '78121', 'ID', 'zattarge2p@hostgator.com', NULL),
	(236, 1159, 'shipping', 'Zelda', 'Attarge', NULL, 'Jl purnama 1 komp purnama 5', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(237, 1160, 'billing', 'Thekla', 'Sherrock', NULL, 'Sui Rengas', NULL, 'Medan', 'SU', '20214', 'ID', 'tsherrock1a@friendfeed.com', NULL),
	(238, 1160, 'shipping', 'Thekla', 'Sherrock', NULL, 'Sui Rengas', NULL, 'Medan', 'SU', '20214', 'ID', NULL, NULL),
	(239, 1161, 'billing', 'Clarey', 'Badwick', NULL, 'Jl purnama1 gg purnama 1', NULL, 'Pontianak', 'KB', '78121', 'ID', 'cbadwick2q@ox.ac.uk', NULL),
	(240, 1161, 'shipping', 'Clarey', 'Badwick', NULL, 'Jl purnama1 gg purnama 1', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(241, 1162, 'billing', 'Simone', 'Stormes', NULL, 'Belawan 1', NULL, 'Medan', 'SU', '20411', 'ID', 'sstormes1b@linkedin.com', NULL),
	(242, 1162, 'shipping', 'Simone', 'Stormes', NULL, 'Belawan 1', NULL, 'Medan', 'SU', '20411', 'ID', NULL, NULL),
	(243, 1163, 'billing', 'Catarina', 'Kingsnod', NULL, 'jl karya baru no 3', NULL, 'Pontianak', 'KB', '78121', 'ID', 'ckingsnod2r@cnet.com', NULL),
	(244, 1163, 'shipping', 'Catarina', 'Kingsnod', NULL, 'jl karya baru no 3', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(245, 1164, 'billing', 'Catarina', 'Kingsnod', NULL, 'jl karya baru no 3', NULL, 'Pontianak', 'KB', '78121', 'ID', 'ckingsnod2r@cnet.com', NULL),
	(246, 1164, 'shipping', 'Catarina', 'Kingsnod', NULL, 'jl karya baru no 3', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(247, 1165, 'billing', 'Dacie', 'Leeman', NULL, 'Jl M sohor', NULL, 'Pontianak', 'KB', '78121', 'ID', 'dleeman0@hatena.ne.jp', NULL),
	(248, 1165, 'shipping', 'Dacie', 'Leeman', NULL, 'Jl M sohor', NULL, 'Pontianak', 'KB', '78121', 'ID', NULL, NULL),
	(249, 1166, 'billing', 'Giana', 'Pesterfield', NULL, 'Jl putri darahitam', NULL, 'Pontianak', 'KB', '78116', 'ID', 'gpesterfield1@prlog.org', NULL),
	(250, 1166, 'shipping', 'Giana', 'Pesterfield', NULL, 'Jl putri darahitam', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(251, 1167, 'billing', 'Muffin', 'Endean', NULL, 'Jl penjara', NULL, 'Pontianak', 'KB', '78116', 'ID', 'mendean2@w3.org', NULL),
	(252, 1167, 'shipping', 'Muffin', 'Endean', NULL, 'Jl penjara', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(253, 1168, 'billing', 'Jasmine', 'Abrahamson', NULL, 'Jl sepakat 2', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jabrahamson3@ehow.com', NULL),
	(254, 1168, 'shipping', 'Jasmine', 'Abrahamson', NULL, 'Jl sepakat 2', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(255, 1169, 'billing', 'Jasmine', 'Abrahamson', NULL, 'Jl sepakat 2', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jabrahamson3@ehow.com', NULL),
	(256, 1169, 'shipping', 'Jasmine', 'Abrahamson', NULL, 'Jl sepakat 2', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(257, 1170, 'billing', 'Jacquelynn', 'Propper', NULL, 'Jl sepakat 2 ujung', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jpropper4@wunderground.com', NULL),
	(258, 1170, 'shipping', 'Jacquelynn', 'Propper', NULL, 'Jl sepakat 2 ujung', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(259, 1171, 'billing', 'Alixx', 'Billet', NULL, 'jl padat karya', NULL, 'Pontianak', 'KB', '78124', 'ID', 'abillett5@newsvine.com', NULL),
	(260, 1171, 'shipping', 'Alixx', 'Billet', NULL, 'jl padat karya', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(261, 1172, 'billing', 'Jaqcuelin', 'Klaff', NULL, 'Jl reformasi', NULL, 'Pontianak', 'KB', '78124', 'ID', 'jklaff6@phpbb.com', NULL),
	(262, 1172, 'shipping', 'Jaqcuelin', 'Klaff', NULL, 'Jl reformasi', NULL, 'Pontianak', 'KB', '78124', 'ID', NULL, NULL),
	(263, 1173, 'billing', 'Dephine', 'Arntzen', NULL, 'jl alianyang no 7', NULL, 'Pontianak', 'KB', '78116', 'ID', 'darntzen7@weibo.com', NULL),
	(264, 1173, 'shipping', 'Dephine', 'Arntzen', NULL, 'jl alianyang no 7', NULL, 'Pontianak', 'KB', '78116', 'ID', NULL, NULL),
	(265, 1174, 'billing', 'Vaclav', 'Wedge', NULL, 'Jl. Gajah Mada No. 55, Kel. Klojen, Kec. Klojen', NULL, 'Malang', 'JI', '65111', 'ID', 'vwedge1s@typepad.com', NULL),
	(266, 1174, 'shipping', 'Vaclav', 'Wedge', NULL, 'Jl. Gajah Mada No. 55, Kel. Klojen, Kec. Klojen', NULL, 'Malang', 'JI', '65111', 'ID', NULL, NULL),
	(267, 1175, 'billing', 'Berkeley', 'Arnholdt', NULL, 'Jl. Pattimura No. 12A, Kel. Petisah Tengah, Kec. Medan Petisah', NULL, 'Medan', 'SU', '20112', 'ID', 'barnholdt1t@un.org', NULL),
	(268, 1175, 'shipping', 'Berkeley', 'Arnholdt', NULL, 'Jl. Pattimura No. 12A, Kel. Petisah Tengah, Kec. Medan Petisah', NULL, 'Medan', 'SU', '20112', 'ID', NULL, NULL),
	(269, 1176, 'billing', 'Malva', 'Anger', NULL, 'Jl. Cendrawasih No. 34, Kel. Oebobo, Kec. Oebobo', NULL, 'Kupang', 'NT', '85111', 'ID', 'manger1u@blog.com', NULL),
	(270, 1176, 'shipping', 'Malva', 'Anger', NULL, 'Jl. Cendrawasih No. 34, Kel. Oebobo, Kec. Oebobo', NULL, 'Kupang', 'NT', '85111', 'ID', NULL, NULL),
	(271, 1177, 'billing', 'Harcourt', 'Clayson', NULL, 'Jl. Teuku Umar No. 89, Kel. Dauh Puri Klod, Kec. Denpasar Barat', NULL, 'Denpasar', 'BA', '80113', 'ID', 'hclayson1v@yahoo.com', NULL),
	(272, 1177, 'shipping', 'Harcourt', 'Clayson', NULL, 'Jl. Teuku Umar No. 89, Kel. Dauh Puri Klod, Kec. Denpasar Barat', NULL, 'Denpasar', 'BA', '80113', 'ID', NULL, NULL),
	(273, 1178, 'billing', 'Morgana', 'Randal', NULL, 'Jl. Rajawali No. 101, Kel. Ilir Timur I, Kec. Ilir Timur', NULL, 'Palembang', 'SS', '30111', 'ID', 'mrandal1w@latimes.com', NULL),
	(274, 1178, 'shipping', 'Morgana', 'Randal', NULL, 'Jl. Rajawali No. 101, Kel. Ilir Timur I, Kec. Ilir Timur', NULL, 'Palembang', 'SS', '30111', 'ID', NULL, NULL),
	(275, 1179, 'billing', 'Alix', 'Kirkup', NULL, 'Jl. Hasanuddin No. 23, Kel. Ujung Pandang, Kec. Ujung Pandang', NULL, 'Makassar', 'SS', '90111', 'ID', 'akirkup1x@parallels.com', NULL),
	(276, 1179, 'shipping', 'Alix', 'Kirkup', NULL, 'Jl. Hasanuddin No. 23, Kel. Ujung Pandang, Kec. Ujung Pandang', NULL, 'Makassar', 'SS', '90111', 'ID', NULL, NULL),
	(277, 1180, 'billing', 'Blythe', 'Aspinal', NULL, 'Jl. Jendral Sudirman No. 3, Kel. Tembilahan Hulu, Kec. Tembilahan', NULL, 'Indragiri Hilir', 'RI', '29213', 'ID', 'baspinal1y@fc2.com', NULL),
	(278, 1180, 'shipping', 'Blythe', 'Aspinal', NULL, 'Jl. Jendral Sudirman No. 3, Kel. Tembilahan Hulu, Kec. Tembilahan', NULL, 'Indragiri Hilir', 'RI', '29213', 'ID', NULL, NULL),
	(279, 1181, 'billing', 'Claresta', 'Alway', NULL, 'Jl. Sisingamangaraja No. 45, Kel. Pandan, Kec. Pandan', NULL, 'Tapanuli Tengah', 'SU', '22611', 'ID', 'calway1z@wix.com', NULL),
	(280, 1181, 'shipping', 'Claresta', 'Alway', NULL, 'Jl. Sisingamangaraja No. 45, Kel. Pandan, Kec. Pandan', NULL, 'Tapanuli Tengah', 'SU', '22611', 'ID', NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
